config/routes.rb
Runnr::Application.routes.draw do
  root 'workouts#index'

  get 'workouts/count' => 'workouts#count', as: :count
  get 'workouts/average_speed' => 'workouts#average_speed', as: :average_speed
  get 'workouts/average_per_week' => 'workouts#average_per_week', as: :average_per_week
  get 'workouts/statistics' => 'workouts#statistics', as: :workout_statistics

  resources :workouts

  

end

app/models/workout.rb
class Workout < ActiveRecord::Base

  validates :date, presence: true
  validates :distance, presence: true, numericality: true
  validates :comment, length: { maximum: 500 }
  validate :duration_string_format, on: :create
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }

  attr_accessor :duration_string

  def self.average_speed
    self.count == 0 ? 0 : self.sum('distance') / (self.sum('duration') / 3600.0)
  end

  def self.average_per_week
    self.count == 0 ? 0 : self.count.to_f / (Date.parse(self.maximum('date').to_s).cweek - Date.parse(self.minimum('date').to_s).cweek + 1)
  end

  def time_period
    @time_period ||= TimePeriod.from_seconds(duration)
  end

  def time_period=(string)
    self.duration = TimePeriod.from_s(string).total_seconds if !string.blank?
  end

  def duration_string=(string)
    if !string.blank?
      @duration_string = string
      self.time_period = string
    end
  end

  def duration_string_format
    if !duration_string.nil? && duration_string !~ /\A([0-9]+:){0,2}[0-9]+\z/
      errors.add(:duration, "must be on the format hh:mm:ss, mm:ss or ss")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def count
    @count = Workout.count
    respond_to do |format|
      format.json { render json: {count: @count}}
    end
  end

  def average_speed
    @average_speed = Workout.average_speed
    respond_to do |format|
      format.json { render json: {average_speed: @average_speed}}
    end
  end

  def average_per_week
    @average_per_week = Workout.average_per_week
    respond_to do |format|
      format.json { render json: {average_per_week: @average_per_week}}
    end
  end

  def statistics
    @count = Workout.count
    @average_speed = Workout.average_speed
    @average_per_week = Workout.average_per_week
    respond_to do |format|
      format.json { render json: {count: @count, average_speed: @average_speed, average_per_week: @average_per_week}}
    end

  end

  # GET /workouts
  # GET /workouts.json
  def index
    @workout = Workout.new
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)
    @workouts = Workout.all

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workouts_url, notice: 'Workout was successfully created.' }
        format.json { render json: @workout.attributes }
      else
        format.html { render action: 'index' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:date, :distance, :duration, :comment, :duration_string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Runnr"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body

    .container

      .row
        .span12
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Company 2014

app/views/workouts/_form.html.haml
= form_for @workout, :html => { :class => 'ajax-form form-horizontal' } do |f|
  - if @workout.errors.any?
    .errors.alert.alert-danger
      %ul
        - @workout.errors.full_messages.each do |e|
          %li= e
  .control-group
    = f.label :date, :class => 'control-label'
    .controls
      = f.text_field :date, :class => 'datepicker'
  .control-group
    = f.label :distance, :class => 'control-label'
    .controls
      = f.text_field :distance, :class => 'text_field'
  .control-group
    = f.label :duration, :class => 'control-label'
    .controls
      = f.text_field :duration_string, :class => 'text_field'
  .control-group
    = f.label :comment, :class => 'control-label'
    .controls
      = f.text_field :comment, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), workouts_path, :class => 'btn'

app/views/workouts/edit.html.haml
- model_class = Workout
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/workouts/index.html.haml
- model_class = Workout

.page-header
  %h1=t '.title', :default => "RunnR"

.row
  .span4
    .canvas
      .dummy
      .content
        #count.big_number
        .caption total runs
  .span4
    .canvas
      .dummy
      .content
        #average_speed.big_number
        .caption average speed
  .span4
    .canvas
      .dummy
      .content
        #average_per_week.big_number
        .caption average runs per week

.row
  .span12

    - if @workouts.empty?
      .span6.offset3.well No workouts to show! Register one by using the form bellow:
    - else
      %table.table.table-striped.tablesorter
        %thead
          %tr
            %th= model_class.human_attribute_name(:date)
            %th= model_class.human_attribute_name(:distance)
            %th= model_class.human_attribute_name(:duration)
            %th= model_class.human_attribute_name(:comment)
            %th=t '.actions', :default => t("helpers.actions")
        %tbody#workout_list
          - @workouts.each do |workout|
            %tr
              %td= l workout.date.to_date
              %td= workout.distance
              %td= workout.time_period
              %td= workout.comment
              %td
                = link_to t('.destroy', :default => t("helpers.links.destroy")), workout_path(workout), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

.row
  .span12
    = render :partial => "form"

app/views/workouts/new.html.haml
- model_class = Workout
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/workouts/show.html.haml
- model_class = Workout
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:date) + ':'
  %br
  = @workout.date
%p
  %strong= model_class.human_attribute_name(:distance) + ':'
  %br
  = @workout.distance
%p
  %strong= model_class.human_attribute_name(:duration) + ':'
  %br
  = @workout.duration
%p
  %strong= model_class.human_attribute_name(:comment) + ':'
  %br
  = @workout.comment

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), workouts_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_workout_path(@workout), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), workout_path(@workout), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'